# Batch create GitHub labels for the repo
repo="fuad13579/CareerPilot-StackFellas"

gh label create "frontend"       --repo "$repo" --color "1abc9c" --description "Frontend related"
gh label create "backend"        --repo "$repo" --color "3498db" --description "Backend related"
gh label create "ai-rag"         --repo "$repo" --color "9b59b6" --description "AI (RAG) features"
gh label create "cv-upload"      --repo "$repo" --color "f39c12" --description "CV Upload feature"
gh label create "job-agent"      --repo "$repo" --color "e67e22" --description "Job agent features"
gh label create "fit-score"      --repo "$repo" --color "2ecc71" --description "Fit score calculations"
gh label create "ai-assistant"   --repo "$repo" --color "e84393" --description "AI Assistant features"
gh label create "tracker"        --repo "$repo" --color "636e72" --description "Progress tracker"
gh label create "calendar-todo"  --repo "$repo" --color "00cec9" --description "Calendar/To-do"
gh label create "dashboard"      --repo "$repo" --color "00b894" --description "Dashboard features"
gh label create "docs"           --repo "$repo" --color "b2bec3" --description "Documentation"
gh label create "demo"           --repo "$repo" --color "fdcb6e" --description "Demo related"

gh label create "priority-high"   --repo "$repo" --color "e74c3c" --description "High priority"
gh label create "priority-medium" --repo "$repo" --color "f1c40f" --description "Medium priority"
gh label create "priority-low"    --repo "$repo" --color "2ecc71" --description "Low priority"

gh label create "todo"            --repo "$repo" --color "95a5a6" --description "To do"
gh label create "in-progress"     --repo "$repo" --color "2980b9" --description "Work in progress"
gh label create "blocked"         --repo "$repo" --color "e17055" --description "Blocked"
gh label create "needs-review"    --repo "$repo" --color "9b59b6" --description "Needs review"
gh label create "done"            --repo "$repo" --color "27ae60" --description "Done"

gh label create "feature"         --repo "$repo" --color "1abc9c" --description "New feature"
gh label create "bug"             --repo "$repo" --color "e74c3c" --description "Bug, error, or issue"
gh label create "enhancement"     --repo "$repo" --color "f1c40f" --description "Enhancement"
gh label create "design"          --repo "$repo" --color "fd79a8" --description "Design"
gh label create "refactor"        --repo "$repo" --color "636e72" --description "Refactor"
gh label create "testing"         --repo "$repo" --color "0984e3" --description "Testing related"
gh label create "integration"     --repo "$repo" --color "00b894" --description "Integration work"
gh label create "deployment"      --repo "$repo" --color "6c5ce7" --description "Deployment/DevOps"